### PR TITLE
Update binding to 1.5.0

### PR DESCRIPTION
**Pull request by Guiorgy**
Updated bindings and README (included license notice as required by APACHE-2.0)

Also edited the source java before compiling:
* Bumbped gradle plugin to 3.1.2
* Bumped TargetSDK to 28
* Bumped BuildTools to 28.0.0

Edit: changed the sample app icon to 

Edit2: elye actually released 1.5.0, but didnt tag it in github release, so I missed it initially. I recompiled the arr with 1.5.0 now.

### CODE REVIEW

**Review by martijn00 — APPROVED** [review]

**Comment by Guiorgy** [comment]
@martijn00, also update the nuget package please.

**Comment by martijn00** [comment]
@Guiorgy i have to update some more to make it possible to get this to nuget.

**Comment by martijn00** [comment]
@Guiorgy I've committed the updates to the structure and published a new version to nuget: https://www.nuget.org/packages/Xam.Plugins.Android.LoaderView/1.5.0

**Comment by Guiorgy** [comment]
@martijn00, great, thanks a lot! 👍

**Pull request merged**
